// AUTO-GENERATED by scripts/gen-dictionary.mjs — do not edit by hand.
// To add translations, re-run the generator after editing the CORE map below,
// or append new { zh: { en, ru, es, pt, ar, fr, hi } } entries directly here.
import type { I18nEntry } from "./i18n-types";

export const I18N_DICT: Record<string, I18nEntry> = {
  "zh-CN": {
    "en": "en-US"
  },
  "🚜": {
    "en": "🚜"
  },
  "zh": {
    "en": "en"
  },
  "免费版": {
    "en": "Free"
  },
  "¥0/年": {
    "en": "¥0/yr"
  },
  "永久免费": {
    "en": "Always Free"
  },
  "品牌收录于品牌库": {
    "en": "Brand listed in directory"
  },
  "5台展品上线": {
    "en": "5 exhibits online"
  },
  "中文展示": {
    "en": "Chinese language"
  },
  "基础浏览量统计": {
    "en": "Basic page views"
  },
  "邮箱询盘通知": {
    "en": "Email inquiry alerts"
  },
  "免费开通": {
    "en": "Start Free"
  },
  "Pro": {
    "en": "Pro"
  },
  "¥380/年": {
    "en": "¥380/yr"
  },
  "日均¥1.04": {
    "en": "¥1.04/day"
  },
  "品牌库优先收录": {
    "en": "Priority brand listing"
  },
  "20台展品": {
    "en": "20 exhibits"
  },
  "中文+英文双语": {
    "en": "Chinese + English"
  },
  "3条产品视频": {
    "en": "3 product videos"
  },
  "月度浏览/询盘报告": {
    "en": "Monthly analytics report"
  },
  "邮件+短信询盘通知": {
    "en": "Email + SMS alerts"
  },
  "开通Pro": {
    "en": "Get Pro"
  },
  "旗舰版": {
    "en": "Flagship"
  },
  "¥980/年": {
    "en": "¥980/yr"
  },
  "日均¥2.68": {
    "en": "¥2.68/day"
  },
  "品牌库置顶展示": {
    "en": "Top brand placement"
  },
  "50台展品": {
    "en": "50 exhibits"
  },
  "中/英/俄三语": {
    "en": "Chinese/English/Russian"
  },
  "10条产品视频": {
    "en": "10 product videos"
  },
  "周度报告+竞品对比": {
    "en": "Weekly report + competitor"
  },
  "优先SEO排名": {
    "en": "Priority SEO ranking"
  },
  "月轮播推荐位": {
    "en": "Monthly featured slot"
  },
  "开通旗舰": {
    "en": "Get Flagship"
  },
  "战略版": {
    "en": "Strategic"
  },
  "¥2,880/年": {
    "en": "¥2,880/yr"
  },
  "日均¥7.89": {
    "en": "¥7.89/day"
  },
  "品牌库首页推荐": {
    "en": "Homepage featured"
  },
  "无限展品": {
    "en": "Unlimited exhibits"
  },
  "全8语种覆盖": {
    "en": "All 8 languages"
  },
  "无限视频+VR展示": {
    "en": "Unlimited video + VR"
  },
  "实时数据+行业对比": {
    "en": "Real-time + industry data"
  },
  "SEO置顶+品牌词保护": {
    "en": "Top SEO + brand term"
  },
  "季度专题置顶位": {
    "en": "Quarterly featured"
  },
  "1对1客户经理": {
    "en": "Dedicated account mgr"
  },
  "联系开通": {
    "en": "Contact Us"
  },
  "品牌已收录": {
    "en": "Brands Listed"
  },
  "配件入库": {
    "en": "Parts in Stock"
  },
  "品类手册": {
    "en": "Manuals"
  },
  "语种覆盖": {
    "en": "Languages"
  },
  "月均询盘": {
    "en": "Avg Monthly Inquiries"
  },
  "地头展背书": {
    "en": "Field Expo Heritage"
  },
  "✨ 品牌入库 · 全球可见": {
    "en": "✨ Brands In · World Sees"
  },
  "开通您的自助展台": {
    "en": "Open Your Self-Expo Booth"
  },
  "5分钟完成注册，自动生成品牌专属页面，纳入「永不落幕的农机世界展会」体系": {
    "en": "5-minute registration, auto-generated brand page, join the Always-On Expo system."
  },
  "为什么选择自助展台？": {
    "en": "Why Choose Self-Expo Booth?"
  },
  "永久在线": {
    "en": "Always Online"
  },
  "不受线下展会时间限制，24小时×365天持续曝光，买家随时访问": {
    "en": "24/7/365 global exposure, buyers visit anytime"
  },
  "自主发布": {
    "en": "Self-Publish"
  },
  "品牌信息、展品、视频、联系方式全部自助管理，实时更新": {
    "en": "Manage brand info, products, videos, and contacts — all self-service"
  },
  "多语种展示": {
    "en": "Multi-Language"
  },
  "从中文到8语种，覆盖200+国家买家，Pro版起即含英/俄": {
    "en": "From Chinese to 8 languages, covering 200+ country buyers"
  },
  "数据驱动": {
    "en": "Data-Driven"
  },
  "浏览量、询盘量、来源分析一目了然，优化参展策略": {
    "en": "Page views, inquiries, source analysis — optimize your strategy"
  },
  "选择适合您的版本": {
    "en": "Choose Your Tier"
  },
  "推荐": {
    "en": "Popular"
  },
  "扫码付款": {
    "en": "Scan to Pay"
  },
  "选择版本后，使用微信或支付宝扫码付款，付款确认后24小时内开通": {
    "en": "Scan to pay after tier selection. Activated within 24 hours after payment confirmed."
  },
  "付款后请将截图发送至 932133255@qq.com 或致电 +86 18633878701 确认": {
    "en": "After payment, send screenshot to 932133255@qq.com or call +86 18633878701."
  },
  "5步开通自助展台": {
    "en": "5 Steps to Open Your Booth"
  },
  "注册账号": {
    "en": "Register"
  },
  "填写企业信息，选择版本": {
    "en": "Company info & tier selection"
  },
  "品牌档案": {
    "en": "Brand Profile"
  },
  "上传Logo、简介、定位、品类": {
    "en": "Logo, intro, positioning"
  },
  "发布展品": {
    "en": "List Products"
  },
  "上传机型照片、视频、参数": {
    "en": "Upload products, photos, videos"
  },
  "提交审核": {
    "en": "Submit for Review"
  },
  "AI自动审+人工抽检": {
    "en": "AI review + human spot-check"
  },
  "开通上线": {
    "en": "Go Live!"
  },
  "获得专属品牌页和二维码": {
    "en": "Get your brand page & QR code"
  },
  "已有309个品牌入驻，下一个就是您": {
    "en": "309 Brands Already In — You're Next"
  },
  "品牌入库即获全球曝光。从免费版开始，无风险试水。": {
    "en": "Brand Listing = Global Exposure. Start free, no risk."
  },
  "免费开通→": {
    "en": "Start Free →"
  },
  "浏览展会": {
    "en": "Browse Expo"
  },
  "暂无数据": {
    "en": "No data available"
  },
  "数据洞察中心": {
    "en": "Market Insights Center"
  },
  "实时掌握农机市场动态，数据驱动决策": {
    "en": "Real-time farm machinery market data for data-driven decisions"
  },
  "在售设备": {
    "en": "Active Listings"
  },
  "本期新增": {
    "en": "new this period"
  },
  "平均价格": {
    "en": "Avg Price"
  },
  "万": {
    "en": "k"
  },
  "已售设备": {
    "en": "Sold Equipment"
  },
  "累计成交": {
    "en": "Total sold"
  },
  "询价总数": {
    "en": "Total Inquiries"
  },
  "待处理": {
    "en": "pending"
  },
  "价格指数走势": {
    "en": "Price Index Trend"
  },
  "（基准日 2026-01-01 = 100）": {
    "en": "(Base: Jan 2026 = 100)"
  },
  "环比": {
    "en": "MoM"
  },
  "同比": {
    "en": "YoY"
  },
  "上架趋势": {
    "en": "Listing Trend"
  },
  "品类分布 TOP 10": {
    "en": "Category Distribution TOP 10"
  },
  "品牌热度 TOP 10": {
    "en": "Brand Popularity TOP 10"
  },
  "价格区间分布": {
    "en": "Price Range Distribution"
  },
  "区域分布 TOP 10": {
    "en": "Regional Distribution TOP 10"
  },
  "台": {
    "en": "units"
  },
  "年份分布": {
    "en": "Year Distribution"
  },
  "年份": {
    "en": "Year",
    "ru": "Год",
    "es": "Año",
    "pt": "Ano",
    "ar": "السنة",
    "fr": "Année",
    "hi": "वर्ष"
  },
  "数量": {
    "en": "Count"
  },
  "均价": {
    "en": "Avg Price"
  },
  "套利榜单 TOP 10": {
    "en": "Arbitrage Ranking TOP 10"
  },
  "设备": {
    "en": "Equipment"
  },
  "国内价": {
    "en": "Domestic"
  },
  "国外价": {
    "en": "Foreign"
  },
  "价差%": {
    "en": "Diff%"
  },
  "创立": {
    "en": "Est."
  },
  "进入展位": {
    "en": "Enter Booth"
  },
  "官网": {
    "en": "Website"
  },
  "热销": {
    "en": "HOT"
  },
  "全球标杆馆 · 主馆": {
    "en": "Global Pavilion · Main Hall"
  },
  "品牌": {
    "en": "Brand",
    "ru": "Бренд",
    "es": "Marca",
    "pt": "Marca",
    "ar": "العلامة التجارية",
    "fr": "Marque",
    "hi": "ब्रांड"
  },
  "全球标杆": {
    "en": "Global Benchmark"
  },
  "农机品牌殿堂": {
    "en": "Machinery Hall"
  },
  "约翰迪尔、克拉斯、凯斯、纽荷兰、芬特、麦赛弗格森——全球农机行业的技术标杆与品质参照。汇聚全球顶尖品牌，建立国际最高标准。": {
    "en": "John Deere, CLAAS, Case IH, New Holland, Fendt, Massey Ferguson — the world's leading agricultural machinery benchmarks. Discover international standards and cutting-edge technology."
  },
  "国际品牌": {
    "en": "Global Brands"
  },
  "旗舰·核心·精选": {
    "en": "Flagship · Premium · Selected"
  },
  "标杆机型": {
    "en": "Benchmark Models"
  },
  "最新技术前沿": {
    "en": "Latest Technology"
  },
  "覆盖国家": {
    "en": "Countries"
  },
  "欧美日主要产区": {
    "en": "Major markets"
  },
  "行业年限": {
    "en": "Years of Legacy"
  },
  "百年品牌传承": {
    "en": "Heritage brands"
  },
  "品牌等级": {
    "en": "Tier"
  },
  "全部": {
    "en": "All",
    "ru": "Все",
    "es": "Todos",
    "pt": "Todos",
    "ar": "الكل",
    "fr": "Tous",
    "hi": "सभी"
  },
  "产品品类": {
    "en": "Category"
  },
  "品牌阵容": {
    "en": "Brand Lineup"
  },
  "共": {
    "en": ""
  },
  "个品牌": {
    "en": "brands"
  },
  "清除筛选": {
    "en": "Clear"
  },
  "暂无符合条件的品牌": {
    "en": "No brands match your filters"
  },
  "尝试调整筛选条件": {
    "en": "Try adjusting your filters"
  },
  "标杆机型展示": {
    "en": "Benchmark Models"
  },
  "精选": {
    "en": "Showing"
  },
  "台热门机型": {
    "en": "featured models"
  },
  "全部展厅": {
    "en": "All Showroom"
  },
  "中国制造 vs 国际标杆": {
    "en": "Chinese vs Global Benchmark"
  },
  "想知道中国品牌与国际标杆的差距有多大？进入品类对比厅，横向参数对比，理性决策。": {
    "en": "Want to see how Chinese brands compare to global benchmarks? Visit the Comparison Hall for side-by-side specs."
  },
  "进入品类对比厅": {
    "en": "Comparison Hall"
  },
  "查看中国品牌": {
    "en": "Chinese Brands"
  },
  "确定删除该展品？": {
    "en": "Delete this item?"
  },
  "自助展台管理": {
    "en": "Booth Management"
  },
  "登录后管理您的展品和询盘": {
    "en": "Login to manage your booth"
  },
  "账号": {
    "en": "Username"
  },
  "密码": {
    "en": "Password"
  },
  "登录": {
    "en": "Login",
    "ru": "Войти",
    "es": "Iniciar sesión",
    "pt": "Entrar",
    "ar": "تسجيل الدخول",
    "fr": "Connexion",
    "hi": "लॉग इन"
  },
  "新入驻品牌请联系管理员获取账号": {
    "en": "Contact admin for account"
  },
  "我的自助展台": {
    "en": "My Self-Expo Booth"
  },
  "查看展台": {
    "en": "View Booth"
  },
  "退出": {
    "en": "Logout"
  },
  "展品数": {
    "en": "Items"
  },
  "总浏览": {
    "en": "Views"
  },
  "询盘": {
    "en": "Inquiries"
  },
  "展品管理": {
    "en": "Item Management"
  },
  "添加展品": {
    "en": "Add Item"
  },
  "还没有展品，点击上方添加": {
    "en": "No items yet. Click Add Item."
  },
  "已发布": {
    "en": "Published"
  },
  "草稿": {
    "en": "Draft"
  },
  "编辑": {
    "en": "Edit"
  },
  "编辑展品": {
    "en": "Edit Item"
  },
  "设备类型 *": {
    "en": "Device Type *"
  },
  "例如：拖拉机": {
    "en": "e.g. Tractor"
  },
  "例如：东方红": {
    "en": "e.g. YTO"
  },
  "型号": {
    "en": "Model",
    "ru": "Модель",
    "es": "Modelo",
    "pt": "Modelo",
    "ar": "الموديل",
    "fr": "Modèle",
    "hi": "मॉडल"
  },
  "例如：LX2004": {
    "en": "e.g. LX2004"
  },
  "工作小时": {
    "en": "Hours"
  },
  "价格 (¥)": {
    "en": "Price (CNY)"
  },
  "描述": {
    "en": "Description"
  },
  "机器状况、备注信息...": {
    "en": "Machine condition, notes..."
  },
  "取消": {
    "en": "Cancel",
    "ru": "Отмена",
    "es": "Cancelar",
    "pt": "Cancelar",
    "ar": "إلغاء",
    "fr": "Annuler",
    "hi": "रद्द करें"
  },
  "保存": {
    "en": "Save",
    "ru": "Сохранить",
    "es": "Guardar",
    "pt": "Salvar",
    "ar": "حفظ",
    "fr": "Enregistrer",
    "hi": "सहेजें"
  },
  "您还没有自助展台": {
    "en": "No Booth Yet"
  },
  "请先通过品牌入驻提交申请，审核通过后即可管理展台": {
    "en": "Submit a brand claim to get started."
  },
  "去入驻": {
    "en": "Claim Booth"
  },
  "金融保险服务": {
    "en": "Financial & Insurance Services"
  },
  "农机贷款、交易保险、设备租赁 — 一站式金融服务助力交易": {
    "en": "Equipment loans, trade insurance, leasing — one-stop financial services"
  },
  "贷款": {
    "en": "Loans"
  },
  "保险": {
    "en": "Insurance"
  },
  "租赁": {
    "en": "Leasing"
  },
  "暂无金融产品": {
    "en": "No financial services available"
  },
  "年利率": {
    "en": "Interest Rate"
  },
  "最高额度": {
    "en": "Max Amount"
  },
  "最长期限": {
    "en": "Max Term"
  },
  "月": {
    "en": "mo"
  },
  "首付比例": {
    "en": "Down Payment"
  },
  "保费率": {
    "en": "Premium Rate"
  },
  "立即申请": {
    "en": "Apply Now"
  },
  "申请提交成功！我们会尽快联系您。": {
    "en": "Application submitted! We'll contact you soon."
  },
  "申请失败": {
    "en": "Application failed"
  },
  "请先登录": {
    "en": "Please login first",
    "ru": "Сначала войдите",
    "es": "Inicie sesión primero",
    "pt": "Faça login primeiro",
    "ar": "يرجى تسجيل الدخول أولاً",
    "fr": "Connectez-vous d'abord",
    "hi": "पहले लॉग इन करें"
  },
  "申请": {
    "en": "Apply"
  },
  "关闭": {
    "en": "Close",
    "ru": "Закрыть",
    "es": "Cerrar",
    "pt": "Fechar",
    "ar": "إغلاق",
    "fr": "Fermer",
    "hi": "बंद करें"
  },
  "申请人姓名 *": {
    "en": "Applicant Name *"
  },
  "联系电话 *": {
    "en": "Phone *"
  },
  "邮箱": {
    "en": "Email"
  },
  "公司名称": {
    "en": "Company Name"
  },
  "申请金额 (元) *": {
    "en": "Amount (CNY) *"
  },
  "期限 (月)": {
    "en": "Term (months)"
  },
  "用途说明": {
    "en": "Purpose"
  },
  "申请条件": {
    "en": "Requirements"
  },
  "提交申请": {
    "en": "Submit Application"
  },
  "第28届 · 真机下地 · 实效演示": {
    "en": "28th Edition · Live Demos"
  },
  "河北农机新机具新技术推广演示会": {
    "en": "Hebei Agricultural Machinery Expo"
  },
  "石家庄·元氏县·神雕农机": {
    "en": "Yuanshi County, Shijiazhuang"
  },
  "~20家国内头部农机品牌": {
    "en": "~20 Top Domestic Brands"
  },
  "查看演示时间": {
    "en": "Demo Schedule"
  },
  "浏览品牌库": {
    "en": "Browse Brands"
  },
  "线下实地演示 · 5场作业": {
    "en": "5 Live Field Demos"
  },
  "参展品牌": {
    "en": "Exhibitors"
  },
  "品类覆盖": {
    "en": "Categories"
  },
  "实地作业演示": {
    "en": "Live Demos"
  },
  "线上直播": {
    "en": "Live Streaming"
  },
  "参展企业 & 展品预告": {
    "en": "Exhibitors & Products"
  },
  "企业": {
    "en": "Company"
  },
  "核心展品": {
    "en": "Products"
  },
  "品类": {
    "en": "Category"
  },
  "品牌库已收录": {
    "en": "In Brand Lib"
  },
  "以上为已公布参展企业（仅限来源·北方农业机械公众号），更多企业请以现场为准。": {
    "en": "List based on published information. More exhibitors at the event."
  },
  "实地作业演示时间表": {
    "en": "Live Demo Schedule"
  },
  "神雕农机 · 平台实力": {
    "en": "Platform Strength"
  },
  "品牌收录": {
    "en": "Brands"
  },
  "品牌入库，全球可见": {
    "en": "Brands In, World Sees"
  },
  "入驻神雕农机，参与永不落幕的农机世界展会": {
    "en": "Join Shendiao for the Always-On Expo"
  },
  "进入世界农机博览会": {
    "en": "Enter World Expo"
  },
  "开通自助展台": {
    "en": "Open Self-Expo Booth"
  },
  "品类对比厅 · 功能厅": {
    "en": "Comparison Hall · Function Hall"
  },
  "同品类中外品牌横向参数对比——价格、马力、性能、技术差距一目了然。理性决策，选择最适合的农机。": {
    "en": "Side-by-side comparison of Chinese and international brands by category — price, power, performance, and technology gaps at a glance."
  },
  " 对比": {
    "en": " Comparison"
  },
  "中国品牌": {
    "en": "Chinese Brands"
  },
  "款": {
    "en": "models"
  },
  "暂无中国品牌展品": {
    "en": "No Chinese models"
  },
  "国际标杆": {
    "en": "International"
  },
  "暂无国际品牌展品": {
    "en": "No international models"
  },
  "价格对比摘要": {
    "en": "Price Comparison Summary"
  },
  "中国品牌均价": {
    "en": "Chinese Avg Price"
  },
  "国际品牌均价": {
    "en": "International Avg Price"
  },
  "价格比": {
    "en": "Price Ratio"
  },
  "找到最适合的农机": {
    "en": "Find the Right Machinery"
  },
  "中国品牌解决'买得到、买得起、修得好'，国际品牌解决'极致性能、超大马力'——按需选择。": {
    "en": "Chinese brands solve affordability and availability; international brands deliver peak performance — choose what fits your needs."
  },
  "中国品牌馆": {
    "en": "China Pavilion"
  },
  "国际标杆馆": {
    "en": "Global Pavilion"
  },
  "旗舰": {
    "en": "Flagship"
  },
  "高端": {
    "en": "High"
  },
  "中端": {
    "en": "Mid"
  },
  "标准": {
    "en": "Standard"
  },
  "首页": {
    "en": "Home",
    "ru": "Главная",
    "es": "Inicio",
    "pt": "Início",
    "ar": "الرئيسية",
    "fr": "Accueil",
    "hi": "होम"
  },
  "AI农机工程师认证": {
    "en": "AI Engineer Certification"
  },
  "AI农机工程师认证体系": {
    "en": "AI Agricultural Machinery Engineer Certification"
  },
  "全球首个农机AI操控认证体系，涵盖AI编程、人机协同、多机调度、数据决策等八维技能，五级认证从AI学徒到首席操控师，证书绑定平台派单权限。": {
    "en": "The world's first agricultural machinery AI control certification system, covering 8-dimensional skills including AI programming, human-machine collaboration, multi-machine scheduling, and data-driven decision making. 5-level certification from AI Apprentice to Chief Controller, with certificates linked to platform dispatch authority."
  },
  "AI编程": {
    "en": "AI Programming"
  },
  "农机AI任务编程与参数调优": {
    "en": "Agricultural machinery AI task programming and parameter tuning"
  },
  "人机协同": {
    "en": "Human-Machine Collaboration"
  },
  "人机协同作业策略与应急接管": {
    "en": "Human-machine collaboration strategies and emergency takeover"
  },
  "多机调度": {
    "en": "Multi-Machine Scheduling"
  },
  "多台农机协同调度与路径优化": {
    "en": "Multi-machine coordination and path optimization"
  },
  "数据决策": {
    "en": "Data-Driven Decision Making"
  },
  "作业数据分析与决策优化": {
    "en": "Operational data analysis and decision optimization"
  },
  "传统操控": {
    "en": "Traditional Operation"
  },
  "农机基础操控与田间作业": {
    "en": "Basic machinery operation and field work"
  },
  "安全规范": {
    "en": "Safety Standards"
  },
  "农机安全操作规范与风险评估": {
    "en": "Machinery safety protocols and risk assessment"
  },
  "维护保养": {
    "en": "Maintenance"
  },
  "农机日常维护与故障排除": {
    "en": "Daily maintenance and troubleshooting"
  },
  "应急处理": {
    "en": "Emergency Response"
  },
  "紧急情况处理与应急预案": {
    "en": "Emergency handling and contingency planning"
  },
  "线下服务网络": {
    "en": "Service Network"
  },
  "全国省级服务中心+县域服务网点，提供设备检测、维修、评估、交易等线下服务": {
    "en": "Provincial service centers and county-level service points across China"
  },
  "服务网点": {
    "en": "Centers"
  },
  "覆盖省份": {
    "en": "Provinces"
  },
  "省级中心": {
    "en": "Provincial"
  },
  "县域网点": {
    "en": "County"
  },
  "搜索省份、城市、网点名称...": {
    "en": "Search province, city, center..."
  },
  "服务网点数据暂时无法加载，请稍后重试": {
    "en": "Service center data is temporarily unavailable. Please try again later."
  },
  "服务网点正在建设中，敬请期待": {
    "en": "Service centers are being set up. Stay tuned."
  },
  "如需线下服务，请拨打客服热线：400-888-XXXX": {
    "en": "For offline service, call: 400-888-XXXX"
  },
  "提交失败，请稍后重试": {
    "en": "Submission failed, please try again"
  },
  "网络错误": {
    "en": "Network error"
  },
  "提交": {
    "ru": "Отправить",
    "es": "Enviar",
    "pt": "Enviar",
    "ar": "إرسال",
    "fr": "Envoyer",
    "hi": "जमा करें",
    "en": ""
  },
  "提交报价": {
    "ru": "Отправить предложение",
    "es": "Enviar oferta",
    "pt": "Enviar proposta",
    "ar": "إرسال عرض",
    "fr": "Envoyer l'offre",
    "hi": "ऑफर जमा करें",
    "en": ""
  },
  "提交您的报价": {
    "ru": "Отправить ваше предложение",
    "es": "Envíe su oferta",
    "pt": "Envie sua proposta",
    "ar": "أرسل عرضك",
    "fr": "Envoyez votre offre",
    "hi": "अपना ऑफर जमा करें",
    "en": ""
  },
  "确认": {
    "ru": "Подтвердить",
    "es": "Confirmar",
    "pt": "Confirmar",
    "ar": "تأكيد",
    "fr": "Confirmer",
    "hi": "पुष्टि करें",
    "en": ""
  },
  "发送": {
    "ru": "Отправить",
    "es": "Enviar",
    "pt": "Enviar",
    "ar": "إرسال",
    "fr": "Envoyer",
    "hi": "भेजें",
    "en": ""
  },
  "返回": {
    "ru": "Назад",
    "es": "Volver",
    "pt": "Voltar",
    "ar": "رجوع",
    "fr": "Retour",
    "hi": "वापस",
    "en": ""
  },
  "搜索": {
    "ru": "Поиск",
    "es": "Buscar",
    "pt": "Buscar",
    "ar": "بحث",
    "fr": "Rechercher",
    "hi": "खोजें",
    "en": ""
  },
  "筛选": {
    "ru": "Фильтр",
    "es": "Filtrar",
    "pt": "Filtrar",
    "ar": "تصفية",
    "fr": "Filtrer",
    "hi": "फ़िल्टर",
    "en": ""
  },
  "查看": {
    "ru": "Просмотр",
    "es": "Ver",
    "pt": "Ver",
    "ar": "عرض",
    "fr": "Voir",
    "hi": "देखें",
    "en": ""
  },
  "详情": {
    "ru": "Подробности",
    "es": "Detalles",
    "pt": "Detalhes",
    "ar": "التفاصيل",
    "fr": "Détails",
    "hi": "विवरण",
    "en": ""
  },
  "更多": {
    "ru": "Ещё",
    "es": "Más",
    "pt": "Mais",
    "ar": "المزيد",
    "fr": "Plus",
    "hi": "अधिक",
    "en": ""
  },
  "联系": {
    "ru": "Связаться",
    "es": "Contactar",
    "pt": "Contatar",
    "ar": "اتصال",
    "fr": "Contacter",
    "hi": "संपर्क करें",
    "en": ""
  },
  "注册": {
    "ru": "Регистрация",
    "es": "Registrarse",
    "pt": "Cadastrar",
    "ar": "تسجيل",
    "fr": "S'inscrire",
    "hi": "रजिस्टर",
    "en": ""
  },
  "加载中": {
    "ru": "Загрузка",
    "es": "Cargando",
    "pt": "Carregando",
    "ar": "جارٍ التحميل",
    "fr": "Chargement",
    "hi": "लोड हो रहा है",
    "en": ""
  },
  "待审核": {
    "ru": "На проверке",
    "es": "Pendiente de revisión",
    "pt": "Aguardando revisão",
    "ar": "بانتظار المراجعة",
    "fr": "En attente",
    "hi": "समीक्षा लंबित",
    "en": ""
  },
  "已通过": {
    "ru": "Одобрено",
    "es": "Aprobado",
    "pt": "Aprovado",
    "ar": "تمت الموافقة",
    "fr": "Approuvé",
    "hi": "स्वीकृत",
    "en": ""
  },
  "已拒绝": {
    "ru": "Отклонено",
    "es": "Rechazado",
    "pt": "Rejeitado",
    "ar": "مرفوض",
    "fr": "Rejeté",
    "hi": "अस्वीकृत",
    "en": ""
  },
  "进行中": {
    "ru": "В процессе",
    "es": "En curso",
    "pt": "Em andamento",
    "ar": "قيد التنفيذ",
    "fr": "En cours",
    "hi": "प्रगति पर",
    "en": ""
  },
  "已完成": {
    "ru": "Завершено",
    "es": "Completado",
    "pt": "Concluído",
    "ar": "مكتمل",
    "fr": "Terminé",
    "hi": "पूर्ण",
    "en": ""
  },
  "已成交": {
    "ru": "Продано",
    "es": "Vendido",
    "pt": "Vendido",
    "ar": "تم البيع",
    "fr": "Vendu",
    "hi": "बिका",
    "en": ""
  },
  "已取消": {
    "ru": "Отменено",
    "es": "Cancelado",
    "pt": "Cancelado",
    "ar": "ملغى",
    "fr": "Annulé",
    "hi": "रद्द",
    "en": ""
  },
  "已接受": {
    "ru": "Принято",
    "es": "Aceptado",
    "pt": "Aceito",
    "ar": "مقبول",
    "fr": "Accepté",
    "hi": "स्वीकृत",
    "en": ""
  },
  "已过期": {
    "ru": "Истекло",
    "es": "Expirado",
    "pt": "Expirado",
    "ar": "منتهي الصلاحية",
    "fr": "Expiré",
    "hi": "समाप्त",
    "en": ""
  },
  "待付款": {
    "ru": "Ожидает оплаты",
    "es": "Pendiente de pago",
    "pt": "Aguardando pagamento",
    "ar": "بانتظار الدفع",
    "fr": "En attente de paiement",
    "hi": "भुगतान लंबित",
    "en": ""
  },
  "已付款": {
    "ru": "Оплачено",
    "es": "Pagado",
    "pt": "Pago",
    "ar": "مدفوع",
    "fr": "Payé",
    "hi": "भुगतान किया गया",
    "en": ""
  },
  "运输中": {
    "ru": "В пути",
    "es": "En tránsito",
    "pt": "Em trânsito",
    "ar": "قيد الشحن",
    "fr": "En transit",
    "hi": "परिवहन में",
    "en": ""
  },
  "报价": {
    "ru": "Предложение",
    "es": "Oferta",
    "pt": "Proposta",
    "ar": "عرض",
    "fr": "Offre",
    "hi": "ऑफर",
    "en": ""
  },
  "还价": {
    "ru": "Встречное предложение",
    "es": "Contraoferta",
    "pt": "Contraproposta",
    "ar": "عرض مضاد",
    "fr": "Contre-offre",
    "hi": "काउंटर-ऑफर",
    "en": ""
  },
  "卖家还价": {
    "ru": "Встречное предложение продавца",
    "es": "Contraoferta del vendedor",
    "pt": "Contraproposta do vendedor",
    "ar": "عرض البائع المضاد",
    "fr": "Contre-offre du vendeur",
    "hi": "विक्रेता का काउंटर-ऑफर",
    "en": ""
  },
  "议价": {
    "ru": "Торг",
    "es": "Negociación",
    "pt": "Negociação",
    "ar": "تفاوض",
    "fr": "Négociation",
    "hi": "मोल-भाव",
    "en": ""
  },
  "拍卖": {
    "ru": "Аукцион",
    "es": "Subasta",
    "pt": "Leilão",
    "ar": "مزاد",
    "fr": "Enchère",
    "hi": "नीलामी",
    "en": ""
  },
  "询价": {
    "ru": "Запрос",
    "es": "Consulta",
    "pt": "Consulta",
    "ar": "استفسار",
    "fr": "Demande",
    "hi": "पूछताछ",
    "en": ""
  },
  "询价中": {
    "ru": "Открыт",
    "es": "Abierta",
    "pt": "Aberta",
    "ar": "مفتوح",
    "fr": "Ouverte",
    "hi": "खुला",
    "en": ""
  },
  "成交价": {
    "ru": "Цена сделки",
    "es": "Precio de venta",
    "pt": "Preço do negócio",
    "ar": "سعر البيع",
    "fr": "Prix de vente",
    "hi": "सौदा मूल्य",
    "en": ""
  },
  "要价": {
    "ru": "Запрашиваемая цена",
    "es": "Precio pedido",
    "pt": "Preço pedido",
    "ar": "السعر المطلوب",
    "fr": "Prix demandé",
    "hi": "मांग मूल्य",
    "en": ""
  },
  "卖家要价": {
    "ru": "Запрашиваемая цена продавца",
    "es": "Precio pedido del vendedor",
    "pt": "Preço pedido do vendedor",
    "ar": "السعر المطلوب من البائع",
    "fr": "Prix demandé par le vendeur",
    "hi": "विक्रेता का मांग मूल्य",
    "en": ""
  },
  "公告": {
    "ru": "Уведомление",
    "es": "Aviso",
    "pt": "Aviso",
    "ar": "إشعار",
    "fr": "Avis",
    "hi": "सूचना",
    "en": ""
  },
  "公告编号": {
    "ru": "№ уведомления",
    "es": "N.º de aviso",
    "pt": "N.º do aviso",
    "ar": "رقم الإشعار",
    "fr": "N° d'avis",
    "hi": "सूचना सं.",
    "en": ""
  },
  "保证金": {
    "ru": "Залог",
    "es": "Depósito",
    "pt": "Depósito",
    "ar": "وديعة",
    "fr": "Dépôt",
    "hi": "जमा राशि",
    "en": ""
  },
  "预约看车": {
    "ru": "Запись на осмотр",
    "es": "Reservar inspección",
    "pt": "Agendar inspeção",
    "ar": "حجز معاينة",
    "fr": "Réserver une inspection",
    "hi": "निरीक्षण बुक करें",
    "en": ""
  },
  "操作失败": {
    "ru": "Действие не выполнено",
    "es": "Error de acción",
    "pt": "Falha na ação",
    "ar": "فشل الإجراء",
    "fr": "Échec de l'action",
    "hi": "क्रिया विफल",
    "en": ""
  },
  "价格": {
    "ru": "Цена",
    "es": "Precio",
    "pt": "Preço",
    "ar": "السعر",
    "fr": "Prix",
    "hi": "मूल्य",
    "en": ""
  },
  "地区": {
    "ru": "Регион",
    "es": "Región",
    "pt": "Região",
    "ar": "المنطقة",
    "fr": "Région",
    "hi": "क्षेत्र",
    "en": ""
  },
  "状态": {
    "ru": "Статус",
    "es": "Estado",
    "pt": "Status",
    "ar": "الحالة",
    "fr": "Statut",
    "hi": "स्थिति",
    "en": ""
  },
  "类型": {
    "ru": "Тип",
    "es": "Tipo",
    "pt": "Tipo",
    "ar": "النوع",
    "fr": "Type",
    "hi": "प्रकार",
    "en": ""
  },
  "卖家": {
    "ru": "Продавец",
    "es": "Vendedor",
    "pt": "Vendedor",
    "ar": "البائع",
    "fr": "Vendeur",
    "hi": "विक्रेता",
    "en": ""
  },
  "买家": {
    "ru": "Покупатель",
    "es": "Comprador",
    "pt": "Comprador",
    "ar": "المشتري",
    "fr": "Acheteur",
    "hi": "खरीदार",
    "en": ""
  },
  "产品": {
    "ru": "Товар",
    "es": "Producto",
    "pt": "Produto",
    "ar": "المنتج",
    "fr": "Produit",
    "hi": "उत्पाद",
    "en": ""
  },
  "订单": {
    "ru": "Заказ",
    "es": "Pedido",
    "pt": "Pedido",
    "ar": "الطلب",
    "fr": "Commande",
    "hi": "ऑर्डर",
    "en": ""
  },
  "时间": {
    "ru": "Время",
    "es": "Hora",
    "pt": "Hora",
    "ar": "الوقت",
    "fr": "Heure",
    "hi": "समय",
    "en": ""
  },
  "最低接受价": {
    "ru": "Минимальная приемлемая цена",
    "es": "Precio mínimo aceptable",
    "pt": "Preço mínimo aceitável",
    "ar": "الحد الأدنى للقبول",
    "fr": "Prix minimum accepté",
    "hi": "न्यूनतम स्वीकृत मूल्य",
    "en": ""
  },
  "内部最低接受价（仅您可见，不向买家展示）": {
    "ru": "Внутренняя мин. цена (только для вас)",
    "es": "Precio mínimo interno (privado)",
    "pt": "Preço mínimo interno (privado)",
    "ar": "الحد الأدنى الداخلي (خاص)",
    "fr": "Prix plancher interne (privé)",
    "hi": "आंतरिक न्यूनतम मूल्य (निजी)",
    "en": ""
  },
  "向买家还价": {
    "ru": "Встречное предложение покупателям",
    "es": "Contraoferta a compradores",
    "pt": "Contraproposta aos compradores",
    "ar": "عرض مضاد للمشترين",
    "fr": "Contre-offre aux acheteurs",
    "hi": "खरीदारों को काउंटर-ऑफर",
    "en": ""
  },
  "还价金额": {
    "ru": "Сумма встречного предложения",
    "es": "Monto de contraoferta",
    "pt": "Valor da contraproposta",
    "ar": "القيمة المضادة",
    "fr": "Montant de la contre-offre",
    "hi": "काउंटर मूल्य",
    "en": ""
  },
  "还价留言（选填）": {
    "ru": "Сообщение (необязательно)",
    "es": "Mensaje (opcional)",
    "pt": "Mensagem (opcional)",
    "ar": "رسالة (اختياري)",
    "fr": "Message (optionnel)",
    "hi": "संदेश (वैकल्पिक)",
    "en": ""
  },
  "接受此还价": {
    "ru": "Принять это предложение",
    "es": "Aceptar esta oferta",
    "pt": "Aceitar esta proposta",
    "ar": "اقبل هذا العرض",
    "fr": "Accepter cette offre",
    "hi": "इस ऑफर को स्वीकार करें",
    "en": ""
  },
  "输入您的报价金额": {
    "ru": "Введите сумму предложения",
    "es": "Ingrese el monto de su oferta",
    "pt": "Digite o valor da proposta",
    "ar": "أدخل مبلغ عرضك",
    "fr": "Entrez le montant de votre offre",
    "hi": "अपनी ऑफर राशि दर्ज करें",
    "en": ""
  },
  "询价须知": {
    "ru": "Информация о запросе",
    "es": "Aviso de consulta",
    "pt": "Aviso de consulta",
    "ar": "إشعار الاستفسار",
    "fr": "Avis de demande",
    "hi": "पूछताछ सूचना",
    "en": ""
  },
  "询价公告全文": {
    "ru": "Полное объявление запроса",
    "es": "Anuncio completo de consulta",
    "pt": "Anúncio completo de consulta",
    "ar": "نص إشعار الاستفسار الكامل",
    "fr": "Annonce complète de la demande",
    "hi": "पूर्ण पूछताछ घोषणा",
    "en": ""
  },
  "买卖合同模板预览": {
    "ru": "Предпросмотр договора купли-продажи",
    "es": "Vista previa del contrato",
    "pt": "Prévia do contrato",
    "ar": "معاينة عقد البيع",
    "fr": "Aperçu du contrat",
    "hi": "बिक्री अनुबंध पूर्वावलोकन",
    "en": ""
  },
  "权属与过户告知": {
    "ru": "Право собственности и передача",
    "es": "Título y transferencia",
    "pt": "Título e transferência",
    "ar": "الملكية والنقل",
    "fr": "Titre et transfert",
    "hi": "स्वामित्व और हस्तांतरण",
    "en": ""
  },
  "车辆信息": {
    "ru": "Информация о технике",
    "es": "Información del vehículo",
    "pt": "Informações do veículo",
    "ar": "معلومات المركبة",
    "fr": "Infos véhicule",
    "hi": "वाहन जानकारी",
    "en": ""
  },
  "品牌型号": {
    "ru": "Марка и модель",
    "es": "Marca y modelo",
    "pt": "Marca e modelo",
    "ar": "العلامة والموديل",
    "fr": "Marque et modèle",
    "hi": "ब्रांड और मॉडल",
    "en": ""
  },
  "参考评估价": {
    "ru": "Оценочная цена",
    "es": "Precio de evaluación",
    "pt": "Preço de avaliação",
    "ar": "سعر التقييم",
    "fr": "Prix d'évaluation",
    "hi": "मूल्यांकन मूल्य",
    "en": ""
  },
  "已知瑕疵": {
    "ru": "Известные недостатки",
    "es": "Defectos conocidos",
    "pt": "Defeitos conhecidos",
    "ar": "عيوب معروفة",
    "fr": "Défauts connus",
    "hi": "ज्ञात खामियां",
    "en": ""
  },
  "发动机工作时长": {
    "ru": "Моточасы двигателя",
    "es": "Horas de motor",
    "pt": "Horas do motor",
    "ar": "ساعات المحرك",
    "fr": "Heures moteur",
    "hi": "इंजन घंटे",
    "en": ""
  },
  "权属文件已上传": {
    "ru": "Документы о праве собственности загружены",
    "es": "Documentos de título cargados",
    "pt": "Documentos de título enviados",
    "ar": "تم رفع وثائق الملكية",
    "fr": "Documents de titre téléversés",
    "hi": "स्वामित्व दस्तावेज़ अपलोड",
    "en": ""
  },
  "平台自营": {
    "ru": "Платформа",
    "es": "Plataforma",
    "pt": "Plataforma",
    "ar": "المنصة",
    "fr": "Plateforme",
    "hi": "प्लेटफ़ॉर्म",
    "en": ""
  },
  "卖出": {
    "ru": "Продать",
    "es": "Vender",
    "pt": "Vender",
    "ar": "بيع",
    "fr": "Vendre",
    "hi": "बेचें",
    "en": ""
  },
  "买入": {
    "ru": "Купить",
    "es": "Comprar",
    "pt": "Comprar",
    "ar": "شراء",
    "fr": "Acheter",
    "hi": "खरीदें",
    "en": ""
  },
  "已结束": {
    "ru": "Завершён",
    "es": "Finalizado",
    "pt": "Encerrado",
    "ar": "انتهى",
    "fr": "Terminé",
    "hi": "समाप्त",
    "en": ""
  },
  "即将开始": {
    "ru": "Скоро",
    "es": "Próximamente",
    "pt": "Em breve",
    "ar": "قريباً",
    "fr": "À venir",
    "hi": "जल्द आ रहा",
    "en": ""
  },
  "我的报价": {
    "ru": "Мои предложения",
    "es": "Mis ofertas",
    "pt": "Minhas propostas",
    "ar": "عروضي",
    "fr": "Mes offres",
    "hi": "मेरे ऑफर",
    "en": ""
  },
  "报名": {
    "ru": "Зарегистрироваться",
    "es": "Inscribirse",
    "pt": "Inscrever-se",
    "ar": "التسجيل",
    "fr": "S'inscrire",
    "hi": "पंजीकरण",
    "en": ""
  },
  "已报名": {
    "ru": "Зарегистрирован",
    "es": "Inscrito",
    "pt": "Inscrito",
    "ar": "مسجل",
    "fr": "Inscrit",
    "hi": "पंजीकृत",
    "en": ""
  },
  "已成交 · {n} 人参与询价": {
    "en": "{n} offerers · Deal closed",
    "ru": "Продано · {n} участников запроса",
    "es": "Vendido · {n} participantes",
    "pt": "Vendido · {n} participantes",
    "ar": "تم البيع · {n} مشاركين",
    "fr": "Vendu · {n} participants",
    "hi": "{n} प्रतिभागियों ने पूछताछ की"
  },
  "已有 {n} 人询价": {
    "en": "{n} offerers",
    "ru": "{n} запросов",
    "es": "{n} consultas",
    "pt": "{n} consultas",
    "ar": "{n} استفسارات",
    "fr": "{n} demandes",
    "hi": "{n} पूछताछ"
  },
  "报价 {n} 人": {
    "en": "{n} offers",
    "ru": "{n} предложений",
    "es": "{n} ofertas",
    "pt": "{n} propostas",
    "ar": "{n} عروض",
    "fr": "{n} offres",
    "hi": "{n} ऑफर"
  },
  "{n} 人报价": {
    "en": "{n} offers",
    "ru": "{n} предложений",
    "es": "{n} ofertas",
    "pt": "{n} propostas",
    "ar": "{n} عروض",
    "fr": "{n} offres",
    "hi": "{n} ऑफर"
  },
  "发动机：{v}": {
    "en": "Engine: {v}",
    "ru": "Двигатель: {v}",
    "es": "Motor: {v}",
    "pt": "Motor: {v}",
    "ar": "المحرك: {v}",
    "fr": "Moteur : {v}",
    "hi": "इंजन: {v}"
  },
  "工时": {
    "en": "h",
    "ru": "ч",
    "es": "h",
    "pt": "h",
    "ar": "ساعة",
    "fr": "h",
    "hi": "घंटे"
  },
  "运转状况以看货为准": {
    "en": "condition per inspection",
    "ru": "состояние по осмотру",
    "es": "según inspección",
    "pt": "conforme inspeção",
    "ar": "حسب المعاينة",
    "fr": "selon inspection",
    "hi": "निरीक्षण के अनुसार"
  },
  "诚意金凭证已上传，卖家将查看。您现在可以提交报价了。": {
    "en": "Earnest deposit receipt uploaded, seller will review. You can now submit your offer.",
    "ru": "Квитанция задатка загружена, продавец проверит. Теперь вы можете отправить предложение.",
    "es": "Comprobante de depósito cargado, el vendedor lo revisará. Ya puede enviar su oferta.",
    "pt": "Comprovante de depósito enviado, o vendedor verificará. Agora você pode enviar sua proposta.",
    "ar": "تم رفع إيصال الوديعة، سيراجعه البائع. يمكنك الآن إرسال عرضك.",
    "fr": "Reçu de dépôt téléversé, le vendeur le vérifiera. Vous pouvez maintenant envoyer votre offre.",
    "hi": "जमा रसीद अपलोड की गई, विक्रेता देखेगा। अब आप अपना ऑफर भेज सकते हैं।"
  },
  "报名信息已提交。您现在可以提交报价了。": {
    "en": "Registration submitted. You can now submit your offer.",
    "ru": "Регистрация отправлена. Теперь вы можете отправить предложение.",
    "es": "Registro enviado. Ya puede enviar su oferta.",
    "pt": "Inscrição enviada. Agora você pode enviar sua proposta.",
    "ar": "تم إرساله. يمكنك الآن إرسال عرضك.",
    "fr": "Inscription envoyée. Vous pouvez maintenant envoyer votre offre.",
    "hi": "पंजीकरण भेजा गया। अब आप अपना ऑफर भेज सकते हैं।"
  },
  "买家 {name} 以 ¥{amount} 成交": {
    "en": "Buyer {name} dealt at ¥{amount}",
    "ru": "Покупатель {name} заключил сделку по ¥{amount}",
    "es": "Comprador {name} cerró trato en ¥{amount}",
    "pt": "Comprador {name} fechou negócio em ¥{amount}",
    "ar": "المشتري {name} أبرم الصفقة بـ ¥{amount}",
    "fr": "Acheteur {name} a conclu l'affaire à ¥{amount}",
    "hi": "खरीदार {name} ने ¥{amount} पर सौदा किया"
  },
  "用户": {
    "en": "User",
    "ru": "Пользователь",
    "es": "Usuario",
    "pt": "Usuário",
    "ar": "مستخدم",
    "fr": "Utilisateur",
    "hi": "उपयोगकर्ता"
  }
};
