name: Deploy to Vercel
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: |
          rm -rf .vercel
          npx vercel deploy --prod \
            --token="${{ secrets.VERCEL_TOKEN }}" \
            --org-id="${{ secrets.VERCEL_ORG_ID }}" \
            --project-id="${{ secrets.VERCEL_PROJECT_ID }}" \
            --yes
